### ISSUE TITLE
[FR] Output to homeassistant

### ISSUE THREAD

**Issue by frog32** [benleb/ad-ench#11]
This app works great but when ever I have many sensors that are being flagged it gets tricky to read.
This is a feature request to feed back the information into home assistant. An example would be to set an input_boolean to true if something was found and put the list of entities into an attribute to facilitate further automations or displaying on a dashboard.

`self.set_state("input_boolean.battery_alert", state="on", attributes={"list":["input_boolean.door_battery", "plant.plant1"]})`

**Comment by benleb** [comment]
sounds like a good improvement 👍 give me a few days ✌️

**Comment by benleb** [comment]
implemented in d9a7ec81eb48e189accced94097f265af4e8a282 - will test this for 1-2 days and craft a new release if everything works. thanks!

**Comment by frog32** [comment]
Looks promising! New release please?
