### ISSUE TITLE
Friendly name

### ISSUE THREAD

**Issue by greetoz** [benleb/ad-ench#13]
The “Show_friendly_name” setting does not seem to work. If I set it to true it still gives me sensor.batteryname instead of Battery Name. Leaving it out of the config also does not work.

**Comment by benleb** [comment]
Which AD and EnCh version are you using? And in which message do you see this?

**Comment by greetoz** [comment]
Hi, I am using the ench 0.6.0 from
HACS. And appdeamon 4 (latest) from the hassio addon store. 

Image below for an example of the iOS notification. It does not show the friendly name but the full sensor name.

![F3260342-43DC-4775-BC9B-BEB7916E268F](https://user-images.githubusercontent.com/6904465/81375135-26ca2c00-9101-11ea-8f96-321c5010615a.jpeg)

**Comment by benleb** [comment]
ah thanks! found the bug :)

regards the parcentage, could you make a new issue for this and describe it there please? thanks!
