### ISSUE TITLE
Show battery percentage in notification

### ISSUE THREAD

**Issue by greetoz** [benleb/ad-ench#15]
Thanks for this great app. But would be nice to include the current battery percentage in the notification. I’ve set the app up to notify when the percentage is below 20% but sometimes wait until 10 or 5 until i replace them battery (depends on the device). Would be nice to see this in the notification. 

Secondly might be a feature to have the option to increase notification frequency when the percentage nears 0%

**Comment by benleb** [comment]
Makes sense :D Thanks!
