### ISSUE TITLE
ANSI(?) codes not rendered correctly on iPhone

### ISSUE THREAD

**Issue by e9henrik** [benleb/ad-ench#16]
The output of EnCh looks garbled on iPhone (app, lock screen notification and home assistant in Google Chrome).

The output I get when running EnCh:
`🔋 Battery low (3): 
device_tracker.[1mgoogle_maps_XXXX[0m, 
device_tracker.[1msm_g970f_2[0m, 
sensor.[1mbattery_level_2[0m `

Is there a way to turn off ANSI codes? Or make them work on iPhone?

Note: I’ve tried both `persistent_notification.create` (sends notification to home assistant) and `notify.notify` (sends to iPhone app). Both have same result.

Thanks!

**Comment by benleb** [comment]
Thanks!
