### ISSUE TITLE
Invalid syntax in line 81

### ISSUE THREAD

**Issue by eifinger** [benleb/ad-ench#19]
Line 81 (66 in release 0.6.2) has an invalid syntax `:=`:
`if (hass_sensor := self.args.get("hass_sensor", None)):`

I would open a PR but I don't quite get the intention of the statement as the configuration option `hass_sensor` is not documented.

**Comment by benleb** [comment]
seems your python version is too old ;)

**Comment by benleb** [comment]
all fixed in https://github.com/benleb/ad-ench/releases/tag/v0.6.3 :)

**Comment by eifinger** [comment]
Thank you!
