### ISSUE TITLE
[Feature request] Run the first check directly when the app is started

### ISSUE THREAD

**Issue by CodeFinder2** [benleb/ad-ench#9]
Hi,

rather a feature request than a bug: it would be cool to run a (battery/unavailable) check once the app is started. This simplifies debugging and I think one would also assume to get notified whether there are such problematic entities directly upon startup. :-)

Guess this should be just a minor thing in the code... :see_no_evil: 

Thanks!

**Comment by benleb** [comment]
The first check is run 120s after start. This grace-period is necessary to give slow devices and integrations in Home Assistant a chance to become "available". I will make this value available as config options so you can adjust it to your needs

**Comment by CodeFinder2** [comment]
Thank you! 

Maybe you should add this explanation to the docs as well?
